### ISSUE TITLE
add fallback for not writable cache location

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#117]
Now that we have a separate SimplePie util class, maybe we can investigate how we can solve the warning when the cache directory is not writable, 
Ref: 
 https://wordpress.org/support/topic/class-simplepie-php/ 
 
The approach which I would like to use  

1) Check if the default cache location is writable if is return that and bail.
2) If is not, use a directory inside the uploads folder, called feedzy-cache, you can use -> http://simplepie.org/wiki/reference/simplepie/set_cache_location 
3) if 2 is not possible ( can not create the folder or something similar ), use this to disable cache at all -> http://simplepie.org/wiki/reference/simplepie/enable_cache 

Let me know what do you think about this ? 

Also, if you find any patterns that we can cover using unit tests, go for them.

**Comment by contactashish13** [comment]
@selul actually, feedzy does not use the cache directory because of these 2 lines. It uses the database for caching.
`
$feed->set_cache_class( 'WP_Feed_Cache' );
$feed->set_cache_duration( apply_filters( 'wp_feed_cache_transient_lifetime', $cache_time, $feedURL ) );
`
When I remove these two lines from the code and fetch a feed, I get the error message ./cache is not writable. When these lines are retained, it saves the feed as transient and I don't see the error message.

I suspect customers who get the error have some component that internally uses the default `fetch_feed` method of WP which by default uses the file caching mechanism.

I think this issue is not required. What do you think?

**Comment by selul** [comment]
@contactashish13 can't we somehow force the database cache on all feedzy feed related requests?

**Comment by contactashish13** [comment]
@selul all feedzy requests are being cached in the database. but if some wild plugin/theme uses the default `fetch_feed` method provided by WP, that will end up using the file cache and thus throwing the error. That's what I feel is happening.

**Comment by selul** [comment]
so do you think is another plugin that break ours ?

**Comment by contactashish13** [comment]
That's what it seems like. Users using feedzy might mistake that message to come from feedzy whereas it could be originating from another plugin/theme.

I don't see any other way because feedzy will not really fallback to using the filesystem when we have asked it to use db caching.

What do you think?

**Comment by selul** [comment]
i understand. Let's put this on hold until we get more insights from users.

**Comment by contactashish13** [comment]
@selul ref: https://secure.helpscout.net/conversation/542318800/157188?folderId=1362294. I don't understand how this is happening despite the code explicitly using db caching. Any hints?

**Comment by selul** [comment]
@contactashish13 i dont know either, can you check user website and see if there are any particular plugin that might change this ? I see they gave the parrot.

**Comment by contactashish13** [comment]
waiting for feedback from @UVLabs

**Comment by rodica-andronache** [comment]
@contactashish13 how is this going?

**Comment by contactashish13** [comment]
I didn't even realize this was assigned to me. I don't see it in my project?

**Comment by contactashish13** [comment]
@rodica-andronache actually, this does not need any action because feedzy uses db caching and not file system caching.

**Comment by rodica-andronache** [comment]
@contactashish13 ok, so there was a problem when using WP RSS Aggregator? Is there something that we can do about?

**Comment by contactashish13** [comment]
@rodica-andronache 

> ok, so there was a problem when using WP RSS Aggregator
yes

> Is there something that we can do about?
I'm not sure we can as there is no problem with Feedzy. Do you have any suggestions?

**Comment by rodica-andronache** [comment]
@selul can you help here? I'm not sure what to do

**Comment by selul** [comment]
i think we can leave it open until we gather more insights on this, i understand that the problem might be WP RSS Aggregator but until we find a way of solving this, we can tell users who are getting this error and have Feedzy + WP RSS Aggregator, to disable the one that is causing this.
