### ISSUE TITLE
Blogspot feed considered as invalid

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/feedzy-rss-feeds#218]
a user on wp.org reported to us that a certain feed type is quite troublesome in some cases.

Ticket link -> https://wordpress.org/support/topic/i-cant-include-in-blogspot-sites-in-my-rss-page/#post-11326153

More exactly, this blogspot feed URL (http://thosewhocansee.blogspot.com/feeds/posts/default) is invalid when checked by Feedzy (screenshot -> http://prntscr.com/mzi5nc) but the feed validator at w3c -> https://validator.w3.org/feed/ and simplepie.org managed to clasify it as valid and to display some items as well. 

The feed validator at w3c had a hard time checking this feed (http://thosewhocansee.blogspot.com/feeds/posts/default) and in most cases threw a 503 error on my end. But after some time the feed was validated -> http://prntscr.com/mzi45o

**Comment by contactashish13** [comment]
@SilviuDinu there are 2 aspects to this. 

1. You have tested only with gutenberg and not with classic editor. I have mentioned a few times on slack as well as individually that the testing needs to happen on both so that the bug can be resolved comprehensively (cc @mileamadalin @selul); please ensure that happens. @HardeepAsrani please look at this issue.

2. On classic editor, I get this error (please confirm after your testing)

![image](https://user-images.githubusercontent.com/12953439/55377797-348fa400-5534-11e9-8aba-34bbf48609c0.png)

I have created a new issue for this error #219 and that PR resolves the issue.

**Comment by HardeepAsrani** [comment]
@contactashish13 Few things I noticed:

- This feel is invalid. This issue doesn't happen when I tried with other feeds of Blogger but only this site.

- Default RSS block doesn't work. If you use latest Gutenberg, it comes with a built-in RSS block which also can't display the feed. It fails (without debugging errors), but it still fails.

Seems to be an issue with the feed.

**Comment by contactashish13** [comment]
@HardeepAsrani the feed is not invalid. It works using the shortcode. You can test it and check for yourself. It works in conjunction with the #220. If it works there, it should work with Gutenberg too

**Comment by HardeepAsrani** [comment]
@contactashish13 I tried this https://github.com/Codeinwp/feedzy-rss-feeds/pull/220/files and the same issue happen on both Classic and Gutenberg, the same error. Do we have to set something or it should fix it?

**Comment by contactashish13** [comment]
@HardeepAsrani as mentioned in #219 you have to return true in the filter

**Comment by HardeepAsrani** [comment]
@contactashish13 This feed is working now. However, whatever feed I choose, the frontend looks different than backend. For example, the description isn't visible in frontend on all the feeds, not just this. Did we change something?

**Comment by HardeepAsrani** [comment]
https://github.com/Codeinwp/feedzy-rss-feeds/pull/239
