### ISSUE TITLE
Allow ability to show date/time in WP timezone

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#278]
ref https://secure.helpscout.net/conversation/907859464/197086/

Right now the date fetched from the feed is shown in UTC format therefore dates such as `<pubDate>Tue, 17 Dec 2019 00:00:00 +0100</pubDate>` end up showing as `16 Dec 11 PM`. User should be able to specify if it should be shown in UTC (which is the default), in the local blog timezone or in the raw feed timezone.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/279 allows the ability to add

- `tz=local` for converting the feed time into local time
- `tz=gmt` for converting the feed time into UTC time (default)
- `tz=no` for NOT converting the feed time and assuming that the time in the feed is already in UTC

**Comment by HardeepAsrani** [comment]
@contactashish13 I tried 3.3.8 branch and tried this and it's not working, as shown in the video: https://www.loom.com/share/0e9178cde6524f2087e335af2b0f3949

Am I doing something wrong?

**Comment by contactashish13** [comment]
@HardeepAsrani the dates in the feed are already in UTC. The plugin shows it in UTC by default and `tz=gmt` does the same thing. Your WP install is likely to be in GMT as well if `tz=local` gives you the same. Better to test it out using the feed in the HS ticket in the issue

**Comment by HardeepAsrani** [comment]
@contactashish13 I tried this feed and it seems to be the same: https://flevumrss.flevumcrm.veiligkantoor.com/RSSFeed.aspx?label=flevum%20forum%20network

It turns out that if I set my timezone to UTC + X in settings, it works just fine.

However, if I just set it to a place, like Kolkata, then it doesn't work. It stays the same whether I any location. So that needs to be fixed. Alternatively, I see a better way to allow the user to just define the timezone.

What do you think? Meanwhile, I'll start working on with the current implementation.

**Comment by contactashish13** [comment]
@HardeepAsrani PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/281 (merged) addresses this. Thanks for testing!
