### ISSUE TITLE
[WP 5.4] Feedzy block alignment

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#411]
In WP 5.4 the content of the Feedzy block is not centered anymore

TwentyTwenty
![download](https://user-images.githubusercontent.com/3266155/78024466-18019400-7361-11ea-9ff2-6b85469ab13c.png)

Neve
![Screenshot (2)](https://user-images.githubusercontent.com/3266155/78024729-8a727400-7361-11ea-82fd-adb04a2aea4d.png)

**Comment by rodica-andronache** [comment]
@contactashish13 @DanyCaissy I think we should release this https://github.com/Codeinwp/feedzy-rss-feeds/pull/410 only after this issue is fixed

**Comment by contactashish13** [comment]
@rodica-andronache none of the elements are now centered in 5.4. You can compare the shortcode block well. Thus we should go along with the same alignment as other blocks.

I have centered the spinner and made a few UI changes so that the block looks more presentable: https://github.com/Codeinwp/feedzy-rss-feeds/pull/412

![image](https://user-images.githubusercontent.com/12953439/78531617-656b7e80-7803-11ea-94e7-8a8a8a248afb.png)


@rodica-andronache @DanyCaissy  I don't think we should hold such releases that do not severely affect functionality - it may send out the wrong signal to customers who may think our plugin does not support the new version.

**Comment by rodica-andronache** [comment]
@contactashish13 I've released the update so that wouldn't be a problem anymore.

For this, I think there are still small things we could do ( leaving the block left aligned like the others ).
For reference, this is how the block looks on WP 5.3
![download](https://user-images.githubusercontent.com/3266155/78762119-24eb3c80-798c-11ea-872e-0ccc87eb01a6.png)

With the new fixes you've done:
- you've removed the "Click here to check if the feed is valid.." message which I think should stay, and be positioned under the input, as before
- the Load Feed button could have the same style as before to make it look like a button

How it looks now in WP 5.4
![download (1)](https://user-images.githubusercontent.com/3266155/78762525-a0e58480-798c-11ea-9319-3a01f0b02309.png)
![download (2)](https://user-images.githubusercontent.com/3266155/78762549-a773fc00-798c-11ea-9ef2-236d651ef13e.png)

**Comment by contactashish13** [comment]
@rodica-andronache if you hover over the icon you will see the entire "click here to...". Once you validate a URL and if it turns out to be invalid, the message "invalid feeds will not..." is shown. Is that not the behavior you see?

**Comment by contactashish13** [comment]
have fixed the button and added a text to the link

![image](https://user-images.githubusercontent.com/12953439/79944803-158ae980-848a-11ea-987e-4d223d1f880e.png)
