### ISSUE TITLE
evaluate every shortcode param and make sure it's mapped to elementor/block widget

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#709]
Hey, 

I would like to review every possible shortcode param that feedzy support and make sure we have that mapped in the block or elementor widget . 

One thing that I saw that we don't have is the follow attribute. 

Ideally, this should be done sustainably where the group of settings is re-used across all contexts, i.e block/shortcode/widget. In this regard if we ever want to add new options, we just change in one place and that should be propagated to every context. 

@girishpanchal30 let me know if everything is clear before going into dev.

**Comment by girishpanchal30** [comment]
Hey @selul,
After reviewing all shortcode attributes, it appears that the block, shortcode, and widget already contain all necessary attributes.

1) feeds - **All**
2) max - **All**
3) feed_title - **All**
4) target - **All**
5) follow - **Shortcode, Widget**
6) title - **All**
7) meta - **All**
8) multiple_meta - **Shortcode, Block**
9) summary - **All**
10) summarylength - **All**
11) thumb - **All**
12) default - **All**
13) size - **All**
14) keywords_title - **All**
15) keywords_inc - **Shortcode**
16) keywords_inc_on - **All**
17) keywords_exc_on - **All**
18) refresh - **All**
19) sort - **All**
20) http - **All**
21) error_empty - **Shortcode, Widget**
22) amp - Shortcode
23) offset - **All**
24) className, classname - **Shortcode**
25) lazy - **All**
26) _dryrun_ - **Shortcode**
27) _dry_run_tags_ - **Shortcode**
28) from_datetime - **All**
29) to_datetime - **All**

> Ideally, this should be done sustainably where the group of settings is re-used across all contexts, i.e block/shortcode/widget. In this regard if we ever want to add new options, we just change in one place and that should be propagated to every context.

Yes, however, it doesn't appear possible to manage all options in one location because each context has a different method to register options.

Let me know if you have any suggestions for this.

Thanks

**Comment by selul** [comment]
@girishpanchal30 let's make sure we have support in ALL for all of them. 

As for their registration, my goal would have been if we can have a config variable where we can define those and based on the context register those different. If this is too complicated and might required more than 1 week of work, we can drop it and just make sure we have support for all in all contexts ( shortcode/block/widget )

**Comment by girishpanchal30** [comment]
Hey @selul,

I've added the below options for all contexts and now it seems all options are working fine.

1) _dryrun_
2) _dry_run_tags_
3) className
4) error_empty
5) multiple_meta
6) follow

> If this is too complicated and might required more than 1 week of work.

Yes, this will time taking task because there are different methods and different block/widget field names.

Please review this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/721 and let me know if I've missed any shortcode options

Thanks

**Comment by selul** [comment]
Looks good, thank you!
