### ISSUE TITLE
Reusing Otter's Feedback Mechanism in Feedzy's Importing Editor

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#774]
### What problem does this address?

We currently have an efficient feedback sharing system in Otter. A similar system can be utilized within Feedzy's importing editor interface. This will enable us to gain valuable insights from users, thereby enhancing our ability to make more user-centric improvements.

@vytisbulkevicius

@Codeinwp/design-team 

___
### [Figma](https://www.figma.com/file/vJ62MRf3FgOBd1i8WWJeIv/Feedzy?type=design&node-id=2212-4030&mode=design&t=AG3rr0MTDqGyEEsm-11)

**Comment by selul** [comment]
@mghenciu yes, exactly.

**Comment by mghenciu** [comment]
hey, I back with an update. Let me know your thoughts, and after this I'll make a more high fidelity prototype depending on the feedback.

For the initial stage I first tried to **find a good place where to place the feedback area**. 
And based on the assumption that: by reaching the end of the flow, a customer would have something to say about Feedzy (even if he is frustrated with something); I think it would make sense to place it at the end.

There are multiple variations in [Figma](https://www.figma.com/file/vJ62MRf3FgOBd1i8WWJeIv/Feedzy?type=design&node-id=2212-4030&mode=design&t=AG3rr0MTDqGyEEsm-11), with a bigger or a smaller height. The best one I think is this one: 
![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/f4d2637b-ec0a-4d3e-a7c7-c30dec160854)


However, I would still not show this from the beginning when people run Feedzy for the first time - but rather after the user has at least 1 import active. That's because for a new user, Feedzy may be daunting - even if after a few imports he gets used to using it.

### Strategy wise, I suggest this:
-  we deploy this mechanism, and the message is visible to **all users that have at leas 1 import runned**
- the box **is dismissible**, appears for both Free and Pro; is visible both in Edit mode or when creating a New Import
- if the user **dismisses** the box -> **the box will disappear, and appear again after 2-3** months with this message: _You've been using Feedzy for a while. We would love to hear your feedback._
- if the user **Sends a feedback**, the form won't appear anymore (or we can use the 2-3 months strategy as above)


___
### Alternative view
An alternative option, would be to use a beacon style toast, that asks for feedback. But this may be hard to fit over the existing UI without affecting the buttons & same rules will apply in this case, meaning that the toast will be visible under some basic conditions.




<details><summary>Example from G Mail</summary>

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/a9ef7e3d-3eba-4602-95d9-0394e212017a)


 </details>


___
And I have a question about the existing **Help us improve!** tab; how does that one work now in terms of results? should we also replace it with a Textarea form like we do in Otter, or leave it as it is.


cc @JohnPixle

**Comment by selul** [comment]
Thanks for the update, @mghenciu ! I was wondering maybe we can find some solution  to show which will not make this dismissable and show it always, maybe after the first import. I like how we have it otter that the user always have the mechanism at hand.

**Comment by mghenciu** [comment]
The suggestions makes sense Marius, thank you.

I've revised a bit the suggested flow, and made a version where the Feedback area could be visible all the time.
On release I would leave it open by default, but after the first import/visit -> I'll make set to be closed:

https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/23b077b2-8f87-4ac0-9251-60272a2c9c06





___



In case the Open/Close interactions are hard to implement, in an accordion like context - we can go for something more wider like below:
<img width="1070" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/266577d6-300b-4431-9836-b7e17f56baa4">

**Comment by mghenciu** [comment]
ok, got it Marius. I think I understood it the other way, to make it more visible.
How about something like this then, which is very similar to Otter feedback mechanism?


https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/ab3edd63-279a-4bf3-b900-c90ec764d783

**Comment by selul** [comment]
@mghenciu it's perfect from my point of view.

**Comment by mghenciu** [comment]
Awesome, I am glad to hear that.

Maybe we doing the changes, it would also make sense to replace this feedback section on the Support page - to use the same modal and feedback mechanism, so we keep all the things in one place:
<img width="1728" alt="Screenshot 2023-07-17 at 10 57 54" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/2ce07194-f237-4b4d-8946-d7373aa1d443">

Currently this section leads to a Google Form.

**Comment by selul** [comment]
well spotted, agree.

**Comment by girishpanchal30** [comment]
Hey @mghenciu,

I've implemented Otter's Feedback Mechanism in Feedzy, please check this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/793 and do let me know if need any changes.

cc @vytisbulkevicius @selul

Thanks

**Comment by mghenciu** [comment]
Overall looks good, Girish.

I'll just list some things I noticed while testing the Feedzy Modal - compared to the Otter modal, **and made some changes** in code.
Regarding the Accessibility issue, @vytisbulkevicius and/or the QA team can decide if that it required or not.

- ✅ the Text area doesn't have a distinct focus state. Usually (as seen also for Otter) the border in focus mode, has a different color 
- Accessibility wise, either the What info do we collect? and Send feedback buttons don't have a focus state; or it's just not possible to complete this flow using only the Keyboard (going back and forth with the Tab and Shift + Tab)

___
Nice to have (design suggestions)
- ✅ I would add a different hover state for the Help us improve Feedzy text, since right not it get's gray on hover  
- ✅  I think we can make the modal style be consistent with the Feedzy look, meaning that we don't use border radius

**Comment by vytisbulkevicius** [comment]
Thanks for your findings @mghenciu!

@girishpanchal30, we should fix the accesibility issue based on the Mihai's feedback:
- Accessibility wise, either the What info do we collect? and Send feedback buttons don't have a focus state; or it's just not possible to complete this flow using only the Keyboard (going back and forth with the Tab and Shift + Tab)

Also, the "Help us improve Feedzy" button can't be selected with the keyboard either.

I see that Mihai fixed other points mentioned himself. Thanks!

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I've fixed the accessibility issue, @mghenciu Can you please review with the latest commit?

**Comment by mghenciu** [comment]
> @vytisbulkevicius I've fixed the accessibility issue, @mghenciu Can you please review with the latest commit?

**The changes look good**, Girish. 🚀 
Thank you!
