### ISSUE TITLE
Feed not displaying featured image

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#802]
### Description

When using this feed https://lesfrancais.press/feed/, some of the featured images are displayed and some are not, even if the posts that had no featured image in Feedzy, do have one on Simple Pie.

### Step-by-step reproduction instructions

1. Open Feedzy > Import
2. Import this feed https://lesfrancais.press/feed/
3. Add featured image tag
4. Publish and check the changes

### Screenshots, screen recording, code snippet or Help Scout ticket

Screenshot Feedzy:
<img width="1677" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/77dc1438-43fc-4f8c-876f-2b36ac7c118b">

Screenshot SimplePie:
<img width="1206" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/147b9689-a150-4936-94dd-881140bad5cc">

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

I tried to create an import with the mentioned feed and all the imported 10 items have featured image attached.

Can you install the Parrot plugin and enable debug to see the errors from the import if there are any? You can share test instance with me also to check as I can't replicate this problem.

**Comment by AndreeaCristinaRadacina** [comment]
@vytisbulkevicius, sure.
I tested again on a test instance and the result is the same: 6/10 posts don't have featured images.


Info:
Parrot Token: OsUcAzNDuvQlqV-P3
WordPress Login: https://levelkick.s4-tastewp.com/wp-login.php
WordPress Version: 6.3.1
PHP Version: 7.4.33
Site Locale: en_US
Theme: Neve 3.7.2

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

Thanks for sharing, I see it now. I was using an instance with Feedzy PRO also and that's why I got images imported.

@girishpanchal30, do you know why we found images for some of the posts but not for others? I see that now from the 10 items in the feed we find images only for 2 with Feedzy Free version OR when using widget/shortcode.

Example:
https://levelkick.s4-tastewp.com/2023/10/10/flash-quotidien-des-expatries-edition-du-09-10-23/

For other 8/10 we use Feedzy logo as a fallback.

With import feature, when Feedzy PRO is active we find images in the content and use them for the imported items.
But I don't see difference in the XML itself in those posts where images are stored and simple PIE shows them:
https://simplepie.org/demo/?feed=https%3A%2F%2Flesfrancais.press%2Ffeed%2F

**Comment by girishpanchal30** [comment]
@vytisbulkevicius

> With import feature, when Feedzy PRO is active we find images in the content and use them for the imported items.
But I don't see difference in the XML itself in those posts where images are stored and simple PIE shows them:

In PRO we have registered API for image fallback and it fetched images from content.
Ref: https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/admin/feedzy-rss-feeds-import.php#L1728

I'll check and let you know why the image does not fetch in the free version.

Thanks

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

After debugging the code I found some feed item does not have the img `src` attribute and in the free version, we've fetched img from the src attribute.

```
<img data-attachment-id="67819" data-permalink="https://lesfrancais.press/elections-en-pologne-le-conseil-de-leurope-tire-la-sonnette-dalarme/11518500-800x450-1/" data-orig-file="https://lesfrancais.press/wp-content/uploads/11518500-800x450-1.jpg" data-orig-size="1024,578" data-comments-opened="1" data-image-meta='{"aperture":"0","credit":"","camera":"","caption":"","created_timestamp":"0","copyright":"","focal_length":"0","iso":"0","shutter_speed":"0","title":"","orientation":"0"}' data-image-title="Elections en Pologne" data-image-description="<p>">
```

Ref: https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L1785

It happened due to lazy load images and we've added lazy load image support in the PRO version.

Thanks

**Comment by vytisbulkevicius** [comment]
Thanks for the research @girishpanchal30!

It makes sense. cc @AndreeaCristinaRadacina
