### ISSUE TITLE
Questions regarding the General Settings

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#828]
Hi there,

I was testing Feedzy > Settings > General and I found some setting that either don't work as intended, or I don't fully understand their usability (in which case I was wondering if we can rename/rephrase to make them clearer):

Do not add the featured image to the website's RSS feed:

- [ ] I enabled this, applied Purge&Reset on one of my imports, but nothing happened. The featured images are still imported in Feed2Post => if this is expected, we should mention in the name/description that this setting applies to the block/shortcode/widget
- [ ] if I enable this and the featured image will not be imported, the fallback image will be applied? (this doesn't happen for feed2post, even if the description mentions this)
- [ ] if the above settings are not linked as I thought, we should use the same font and dimension for the fallback featured image, e.g., title: Global Fallback Featured Image, description: This image will be used as a featured image when feed items lack one. It will be applied to all imports. To set specific fallback images for each import, refer to [this](https://docs.themeisle.com/article/1964-fallback-image-in-feedzy-rss-feeds) documentation for more information.
- [ ] Disable default style - from the description, I understand that the default style is the one forced by the theme. If I choose to disable this theme's default style, the settings that I configure in the block/shortcode/widget are applied. If that's true, we should either rename the setting to Theme Default Style so that the second phrase is valid ("If disabled, it will be considered..." or change the description because right now it contains two negations.
- [ ] Delete the posts created from all feeds after a number of days - by reading its description, it seems to be applied only to feed2post because only there I have a similar option. If that's the case, we should mention this clearly

**Comment by AndreeaCristinaRadacina** [comment]
Based on the above questions, it is worth considering separating these settings somehow into two parts: Feed to Post general settings and Block/Shortcode/Widget General Settings.

Let me know what you think!

**Comment by vytisbulkevicius** [comment]
Hi @AndreeaCristinaRadacina,

The setting "**Do not add the featured image to the website's RSS feed**" is actually neither about F2P (import functionality) nor about widget/shortcode usage. Well, in a way it's related to F2P more but what it affects is YOUR website's XML RSS Feed, not how it will be displayed on your website but how it will be shown on the XML RSS Feed.

So let's say your website is: andreea.com and if it's WordPress website the XML RSS Feed of your website by default should be accessible as andreea.com/feed where posts from your website are shown in XML format.

So if **Do not add the featured image to the website's RSS feed** is enabled, in that XML format you won't see images of your posts even if they have those.

The fallback image below it:
<img width="558" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/aef0b71f-29f5-4048-8cd8-64f7f527ffca">

Is a separate thing, these functionalities are not connected.


> if I enable this and the featured image will not be imported, the fallback image will be applied? (this doesn't happen for feed2post, even if the description mentions this)

Have you set the fallback featured image and there were items in your feed used for import that did not have images? In that case fallback image should have been used (only when featured image is not available in the source RSS XML Feed itself).
Because I tested this and it works fine for me, if source does not have featured images the fallback image is attached to each imported post.

> if the above settings are not linked as I thought, we should use the same font and dimension for the fallback featured image, e.g., title: Global Fallback Featured Image, description: This image will be used as a featured image when feed items lack one. It will be applied to all imports. To set specific fallback images for each import, refer to [this](https://docs.themeisle.com/article/1964-fallback-image-in-feedzy-rss-feeds) documentation for more information.


I agree, we can make it more clear that these features are not connected. Next to the fallback image it's mentioned Feed2Post but yes, the description below it could be more clear I will create an issue for this.


> Disable default style - from the description, I understand that the default style is the one forced by the theme. If I choose to disable this theme's default style, the settings that I configure in the block/shortcode/widget are applied. If that's true, we should either rename the setting to Theme Default Style so that the second phrase is valid ("If disabled, it will be considered..." or change the description because right now it contains two negations.
Yes, your understanding here is correct.
Here is the issue where it's covered if you want to dig more - https://github.com/Codeinwp/feedzy-rss-feeds/issues/710

>  Delete the posts created from all feeds after a number of days - by reading its description, it seems to be applied only to feed2post because only there I have a similar option. If that's the case, we should mention this clearly
 
 So only F2P creates posts, shortcode/widget usage does not create any posts, you use it INSIDE post or a page, so not sure if naming it after F2P is needed in this case.
 
 Let me know if you have further suggestions or questions.
