### ISSUE TITLE
"Post content" string is imported when Youtube Feed is used

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#842]
### Description

As found by @AndreeaCristinaRadacina here - https://github.com/Codeinwp/feedzy-rss-feeds/issues/841 it seems that when we're using feed and [#item_content] tag, if there is no text content but only video, like in this example, Feedzy imports fixed string "`Post content`" before the video:

<img width="713" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/b6d83514-4d0b-4543-a1dd-c87a4e728f2c">

It shouldn't be happening, even when there is only media content to import, no hardcoded text should be imported.

### Step-by-step reproduction instructions

1. Create an import and use YT feed, for example:
https://www.youtube.com/feeds/videos.xml?channel_id=UCMfPBtm9CWGswAXohT5MFyQ
2. Use [#item_content] tag for the Content
3. Check imported posts, they have hardcoded string above the imported video.

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@vytisbulkevicius The ability to import youtube videos should be available in both free and pro or in pro only?

I see the issue is created in the free repo and we only have a PR for pro.

Youtube import with Feedzy only: https://vertis.d.pr/i/Jj6O7H
Youtube import with Feedzy & Feedzy pro https://vertis.d.pr/i/1Pu0AJ
