### ISSUE TITLE
Feeds marked invalid

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#856]
### Description

A user reported that several feeds are being marked as invalid.

Ref: https://wordpress.org/support/topic/all-my-feeds-marked-invalid-on-update/#post-17344845

### Step-by-step reproduction instructions

1. Go to Feedzy > Feed Categories
2. Create a new category
3. Paste the following feed sources: https://aseannewstoday.com/countries/myanmar/feed/, https://www.frontiermyanmar.net/feed/, https://www.rfa.org/english/news/burma_news/rss2.xml, https://www.aljazeera.com/xml/rss/all.xml, https://www.eastasiaforum.org/category/countries/myanmar/feed/, https://www.thechindwin.com/feed/
4. Click on update

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/Kmj661

If you try to copy one of the invalid feeds and paste it inside the validator, you will see it appends http://%20 in front of the URL. If you eliminate it and only paste the feed URL, it becomes valid.
<img width="1660" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/6862c2e0-830a-41e1-94ef-c4731028c31c">

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Additional information here:

This issue happens when there is space between a semicomma that separates feeds.

So for example if you add all the feeds to a category without a space:
https://aseannewstoday.com/countries/myanmar/feed/,https://www.frontiermyanmar.net/feed/,https://www.rfa.org/english/news/burma_news/rss2.xml,https://www.aljazeera.com/xml/rss/all.xml,https://www.eastasiaforum.org/category/countries/myanmar/feed/,https://www.thechindwin.com/feed/

It works fine.

If you add them with spaces:
https://aseannewstoday.com/countries/myanmar/feed/, https://www.frontiermyanmar.net/feed/, https://www.rfa.org/english/news/burma_news/rss2.xml, https://www.aljazeera.com/xml/rss/all.xml, https://www.eastasiaforum.org/category/countries/myanmar/feed/, https://www.thechindwin.com/feed/

They are removed as invalid.

So it's not related to feeds in use but to space.

Also, when they are successfully saved, even when added without spaces we add spaces after saving, so next time you click update they are removed as invalid.

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina,

I've reviewed this issue and fixed it this PR #858

cc @vytisbulkevicius

Thanks
