### ISSUE TITLE
Item source is Feedzy when using multiple feeds

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#899]
### Description

While working on a ticket, I found that when you're using multiple feed sources in the same import, the source will be "Feedzy" instead of the actual name of the feed.

Not sure if it's a bug or if it's expected.

ref: https://secure.helpscout.net/conversation/2525118325/406402?viewId=212385

### Step-by-step reproduction instructions

1. Go to Feedzy > Imports
2. Create a new import
3. Use the following feeds: https://community.511tactical.com/feed/, https://loadoutroom.com/feed/
4. In the Map Content area, use Item Full Content and Item Source
5. Save and check one of the posts

### Screenshots, screen recording, code snippet or Help Scout ticket

When using only one feed:
<img width="1597" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/b39c17d1-e063-4637-a3c5-36ae94896150"> <br>
When using both:
<img width="1439" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/d7b194eb-f18b-4f83-80ca-281d71b77af3">

### Is the issue you are reporting a regression

No

**Comment by Soare-Robert-Daniel** [comment]
After taking a deep look at this, the full content fetch is done using an endpoint from our server to fetch all the data from the desired feeds. 

The endpoint gives all the collected feeds into a single XML. When there are multiple sources, the `item_source` is set to Feedzy since it is the name of the pages that contain all feeds.

With a single source:

```
item_feed_title: Celebrating Women in Service: International Women’s Day at 5.11 Tactical
tem_feed_link: https://www.511tactical.com/community/celebrating-women-in-service/
item_source_title: 5.11 Community
item_source_link: https://www.511tactical.com/community/
```

With multiple sources:

```
item_feed_title: Celebrating Women in Service: International Women’s Day at 5.11 Tactical
item_feed_link: https://www.511tactical.com/community/celebrating-women-in-service/
item_source_title: Feedzy
item_source_link: https://feedzy.themeisle.com/wp/wp/index.php/feed/feedzyfpv3?token=0837331df9
```

To solve this, I think changing the endpoint from https://github.com/Codeinwp/feedzy-full-post will be required to append the source origin of the feed. But I am not sure what major changes it will be for the parsing mechanism of the endpoint plugin to extract those.

**Comment by vytisbulkevicius** [comment]
Thanks for looking into it @Soare-Robert-Daniel.

Not a big priority, but I would like to have this fixed, I remember some requests about this from our customers in the past as well, so unless it's too complicated to make this change, let's do it.
